version: "3.1"

services:
  printer-api:
    container_name: printer-api
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/Dockerfile.development
    environment:
      DATABASE_URL: ${DOCKER_URL}
      NODE_ENV: development
      PORT: 8001
    volumes:
      - .:/src
    ports:
      - "8001:8001"
      - "161:161/udp"
    env_file:
      - .env
    networks:
      - printgo_network
    depends_on:
      - postgres-printgo
    command: ["sh", "-c", "npx prisma db push && yarn dev"]

  postgres-printgo:
    image: postgres:13
    container_name: postgres-printgo-printer
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: printgo-local
    ports:
      - "5446:5432"
    networks:
      - printgo_network

networks:
  printgo_network:
    name: printgo_network
    driver: bridge
    external: true
