name: Deploy no Render
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  render:
    name: render
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy
        run: curl ${{secrets.RENDER_TRIGGER}}
