name: Análise de Código
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:
    # types: [opened, synchronize, reopened]
    branches:
      - main
      - dev

jobs:
  render:
    name: render
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy
        run: curl ${{secrets.RENDER_TRIGGER}}
