name: Análise de Código

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Checar Versão do Java
        run: java -version

      - name: Instalar Dependências
        run: |
          npm install -g yarn
          yarn install

      - name: Executar Migrations
        run: npx prisma db push
        env:
          DATABASE_URL: postgresql://testuser:testpassword@localhost:5444/testdb

      - name: Executar Linter
        run: yarn lint

      - name: Executar Testes
        run: yarn test:all
        env:
          DATABASE_URL: postgresql://testuser:testpassword@localhost:5444/testdb
          SMPT_HOST: ${{secrets.SMPT_HOST}}
          SMPT_PORT: ${{secrets.SMPT_PORT}}
          SMPT_MAIL: ${{secrets.SMPT_MAIL}}
          SMPT_PASSWORD: ${{secrets.SMPT_PASSWORD}}

      - name: Executar SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=fga-eps-mds-1_2024-1-printgo-printerservice \
            -Dsonar.organization=fga-eps-mds-1 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.java.binaries=./build/classes/java/main
