name: Análise de Código
on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
  pull_request:
    # types: [opened, synchronize, reopened]
    branches:
      - dev
      - main

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Instala dependências
        run: yarn

      - name: Executa linter
        run: yarn lint

      - name: Executa testes e gera cobertura
        run: yarn test:all

      - name: Executa SonarCloud Scan
        if: ${{ always() }}
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
