name: Análise de Código

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
        ports:
          - 5444:5432
        options: >-
          --health-cmd="pg_isready -U testuser -d testdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Instala dependências
        run: yarn install

      - name: Roda Migrations
        run: npx prisma db push
        env:
          DATABASE_URL: postgresql://testuser:testpassword@localhost:5444/testdb

      - name: Executa linter
        run: yarn lint

      - name: Executa testes e gera cobertura
        run: yarn test:all
        env:
          DATABASE_URL: postgresql://testuser:testpassword@localhost:5444/testdb
          SMPT_HOST: ${{secrets.SMPT_HOST}}
          SMPT_PORT: ${{secrets.SMPT_PORT}}
          SMPT_MAIL: ${{secrets.SMPT_MAIL}}
          SMPT_PASSWORD: ${{secrets.SMPT_PASSWORD}}

      - name: Executa SonarCloud Scan
        if: ${{ always() }}
        uses: SonarSource/sonarcloud-github-action@v1.4
        with:
          args: >
            -X
            -Dsonar.projectKey=fga-eps-mds-1_2024-1-printgo-printerservice
            -Dsonar.organization=fga-eps-mds-1
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
